import 'dotenv/config';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import {
  ActionRowBuilder, ButtonBuilder, ButtonStyle, ChannelType, Client, EmbedBuilder,
  Events, GatewayIntentBits, Interaction, ModalBuilder, PermissionFlagsBits, REST, Routes,
  SlashCommandBuilder, StringSelectMenuBuilder, TextInputBuilder, TextInputStyle,
  type ChatInputCommandInteraction, type GuildMember, type TextChannel
} from 'discord.js';

type Team = { name: string; captainId: string; players: string[]; subs: string[]; platform: string; region: string; createdAt: string };
type Lfg = { id: string; ownerId: string; description: string; createdAt: string; open: boolean };
type Db = { ranks: Record<string, string>; teams: Team[]; lfg: Lfg[]; warnings: Record<string, string[]>; config: Record<string, string>; };

const token = process.env.DISCORD_TOKEN;
const clientId = process.env.DISCORD_CLIENT_ID;
if (!token || !clientId) throw new Error('Missing DISCORD_TOKEN or DISCORD_CLIENT_ID. Copy .env.example to .env.');
if (!/^\d{17,20}$/.test(clientId)) throw new Error('DISCORD_CLIENT_ID must be the numeric Application ID from Discord Developer Portal, not a token or Railway project ID.');
if (process.env.DISCORD_GUILD_ID && !/^\d{17,20}$/.test(process.env.DISCORD_GUILD_ID)) throw new Error('DISCORD_GUILD_ID must be the numeric Discord server ID with Developer Mode enabled.');
const dbPath = process.env.CPL_DATA_FILE ?? './cpl-data.json';
const initial: Db = { ranks: {}, teams: [], lfg: [], warnings: {}, config: {} };
let db: Db = existsSync(dbPath) ? { ...initial, ...JSON.parse(readFileSync(dbPath, 'utf8')) } : initial;
const save = () => writeFileSync(dbPath, JSON.stringify(db, null, 2));
const colors = { cyan: 0x38d9f4, blue: 0x2563eb, gold: 0xfacc15, dark: 0x0b1120, red: 0xfb7185, green: 0x4ade80 };
const embed = (title: string, description: string, color = colors.cyan) => new EmbedBuilder().setColor(color).setTitle(title).setDescription(description).setFooter({ text: 'CPL · PLAY. COMPETE. BUILD. WIN.' }).setTimestamp();
const isStaff = (i: ChatInputCommandInteraction) => i.memberPermissions?.has(PermissionFlagsBits.ManageGuild) ?? false;
const replyError = (i: Interaction, text: string) => i.isRepliable() && i.reply({ embeds: [embed('❌ Something went wrong', text, colors.red)], ephemeral: true });
const staffGuard = (i: ChatInputCommandInteraction) => isStaff(i) || Boolean(i.memberPermissions?.has(PermissionFlagsBits.Administrator));
const ranks = ['Copper V','Copper IV','Copper III','Copper II','Copper I','Bronze V','Bronze IV','Bronze III','Bronze II','Bronze I','Silver V','Silver IV','Silver III','Silver II','Silver I','Gold V','Gold IV','Gold III','Gold II','Gold I','Platinum V','Platinum IV','Platinum III','Platinum II','Platinum I','Emerald V','Emerald IV','Emerald III','Emerald II','Emerald I','Diamond V','Diamond IV','Diamond III','Diamond II','Diamond I','Champion'];

const command = (name: string, description: string) => new SlashCommandBuilder().setName(name).setDescription(description);
const commands = [
  command('help','Open the interactive CPL command center'), command('about','About Competitive Play League'), command('ping','Check bot latency'), command('botinfo','Show bot status'),
  command('roles','Open platform, game, player type, LFG, and region roles'),
  command('rank','Set or view your Rainbow Six Siege rank').addStringOption(o => o.setName('value').setDescription('Rank name, e.g. Champion or Emerald II').setRequired(false)),
  command('rankup','Submit a rank-up proof review'), command('lfg','Create a ranked or competitive LFG post'), command('teamfinder','Create a team recruitment post'),
  command('team','Manage your CPL team').addSubcommand(s => s.setName('create').setDescription('Create a team').addStringOption(o => o.setName('name').setDescription('Team name').setRequired(true)).addStringOption(o => o.setName('platform').setDescription('Platform').setRequired(true)).addStringOption(o => o.setName('region').setDescription('Region').setRequired(true))).addSubcommand(s => s.setName('profile').setDescription('View your team')).addSubcommand(s => s.setName('add').setDescription('Add a player').addUserOption(o => o.setName('user').setDescription('Player').setRequired(true))).addSubcommand(s => s.setName('remove').setDescription('Remove a player').addUserOption(o => o.setName('user').setDescription('Player').setRequired(true))).addSubcommand(s => s.setName('leave').setDescription('Leave your team')).addSubcommand(s => s.setName('disband').setDescription('Disband your team')),
  command('register','Submit a tournament registration'), command('maps','Show CPL-approved maps'), command('tournament','Tournament tools').addSubcommand(s => s.setName('list').setDescription('List tournaments')).addSubcommand(s => s.setName('register').setDescription('Register your team')).addSubcommand(s => s.setName('create').setDescription('Create a tournament (staff)')).addSubcommand(s => s.setName('start').setDescription('Start a tournament (staff)')).addSubcommand(s => s.setName('end').setDescription('End a tournament (staff)')),
  command('bracket','View or manage tournament brackets'), command('match','Create or manage a match'), command('stats','View player stats'), command('teamstats','View team statistics'), command('leaderboard','View CPL leaderboards'), command('mvp','Award or view MVPs'),
  command('coach','Open the coaching center'), command('ticket','Open a private support ticket'), command('report','Submit a private player or team report'), command('cheat-report','Submit a private cheating report'), command('payment','View or submit payment status'), command('payout','View payout status'), command('schedule','View the CPL schedule'), command('announce','Send an announcement (staff)'), command('suggest','Submit a community suggestion'),
  command('warn','Warn a member (staff)').addUserOption(o => o.setName('user').setDescription('Member').setRequired(true)).addStringOption(o => o.setName('reason').setDescription('Reason').setRequired(true)), command('warnings','View member warnings (staff)').addUserOption(o => o.setName('user').setDescription('Member').setRequired(true)), command('timeout','Timeout a member (staff)').addUserOption(o => o.setName('user').setDescription('Member').setRequired(true)).addIntegerOption(o => o.setName('minutes').setDescription('Minutes').setRequired(true)), command('kick','Kick a member (staff)').addUserOption(o => o.setName('user').setDescription('Member').setRequired(true)), command('ban','Ban a member (staff)').addUserOption(o => o.setName('user').setDescription('Member').setRequired(true)), command('clear','Clear recent messages (staff)').addIntegerOption(o => o.setName('amount').setDescription('1-100').setRequired(true)),
  command('notifications','Manage notification preferences'), command('config','View CPL configuration (staff)'), command('dashboard','Open the staff control center (staff)'), command('news','View CPL news'), command('clips','View featured CPL clips')
].map(c => c.toJSON());

const rest = new REST({ version: '10' }).setToken(token);
await rest.put(process.env.DISCORD_GUILD_ID ? Routes.applicationGuildCommands(clientId, process.env.DISCORD_GUILD_ID) : Routes.applicationCommands(clientId), { body: commands });
const client = new Client({ intents: [GatewayIntentBits.Guilds, GatewayIntentBits.GuildMembers] });

const helpRows = () => [new ActionRowBuilder<ButtonBuilder>().addComponents(
  new ButtonBuilder().setCustomId('help_member').setLabel('Member').setEmoji('👤').setStyle(ButtonStyle.Secondary), new ButtonBuilder().setCustomId('help_compete').setLabel('Compete').setEmoji('🏆').setStyle(ButtonStyle.Primary), new ButtonBuilder().setCustomId('help_staff').setLabel('Staff').setEmoji('🛡️').setStyle(ButtonStyle.Secondary)
)];
const roleRow = () => [new ActionRowBuilder<StringSelectMenuBuilder>().addComponents(new StringSelectMenuBuilder().setCustomId('role_select').setPlaceholder('Choose your CPL roles').setMinValues(1).setMaxValues(4).addOptions(
  { label: 'PC', value: 'PC', emoji: '🖥️' }, { label: 'Xbox', value: 'Xbox', emoji: '🎮' }, { label: 'PlayStation', value: 'PlayStation', emoji: '🎮' }, { label: 'Competitive Player', value: 'Competitive Player', emoji: '🏆' }, { label: 'Looking for Players', value: 'Looking for Players', emoji: '🎯' }, { label: 'Team Captain', value: 'Team Captain', emoji: '👑' }, { label: 'EU', value: 'EU', emoji: '🌎' }, { label: 'NA', value: 'NA', emoji: '🌎' }
))];
const modal = (id: string, title: string, fields: Array<[string,string,TextInputStyle,boolean]>) => { const m = new ModalBuilder().setCustomId(id).setTitle(title); return m.addComponents(...fields.map(([customId,label,style,required]) => new ActionRowBuilder<TextInputBuilder>().addComponents(new TextInputBuilder().setCustomId(customId).setLabel(label).setStyle(style).setRequired(required)))); };

client.once(Events.ClientReady, c => console.log(`CPL Discord Bot 1 online as ${c.user.tag}`));
client.on(Events.GuildMemberAdd, async member => { const channelId = db.config.welcomeChannel; const channel = channelId ? member.guild.channels.cache.get(channelId) : undefined; if (channel?.isTextBased()) await channel.send({ embeds: [embed('👋 Welcome to CPL!', `Welcome ${member} to the Competitive Play League.\n\n🎭 Get your roles\n🎯 Find teammates\n🏆 Join tournaments\n🎮 Play ranked\n🎓 Find coaching`, colors.cyan)] }).catch(console.error); });

client.on(Events.InteractionCreate, async i => {
  try {
    if (i.isButton()) {
      if (i.customId.startsWith('help_')) { const text = i.customId === 'help_member' ? '`/roles` `/rank` `/lfg` `/team` `/stats` `/ticket` `/suggest`' : i.customId === 'help_compete' ? '`/teamfinder` `/register` `/tournament` `/bracket` `/match` `/leaderboard` `/coach`' : '`/dashboard` `/config` `/announce` `/warn` `/timeout` `/kick` `/ban` `/clear`'; return i.update({ embeds: [embed('CPL COMMAND CENTER', text)], components: helpRows() }); }
      if (i.customId === 'lfg_join') return i.reply({ content: '✅ You joined this LFG. The post owner has been notified.', ephemeral: true });
      if (i.customId === 'ticket_close') { if (i.channel?.isTextBased() && 'send' in i.channel) await i.channel.send({ embeds: [embed('🔒 Ticket closed', 'This ticket will be archived shortly.', colors.gold)] }); return i.reply({ content: 'Ticket closed.', ephemeral: true }); }
      if (i.customId === 'rank_approve' || i.customId === 'rank_reject') return i.update({ embeds: [embed(i.customId === 'rank_approve' ? '✅ Rank approved' : '❌ Rank rejected', 'Staff review decision recorded.', i.customId === 'rank_approve' ? colors.green : colors.red)], components: [] });
    }
    if (i.isStringSelectMenu() && i.customId === 'role_select') { const selected = i.values.map(v => '**' + v + '**').join(', '); return i.reply({ embeds: [embed('✅ Roles selected', 'Selected: ' + selected + '\n\nRole IDs can be mapped in /config for automatic Discord role assignment.')], ephemeral: true }); }
    if (i.isModalSubmit()) {
      if (i.customId === 'lfg_modal') { const lfg: Lfg = { id: `LFG-${Date.now().toString(36).toUpperCase()}`, ownerId: i.user.id, description: i.fields.getTextInputValue('description'), createdAt: new Date().toISOString(), open: true }; db.lfg.push(lfg); save(); const row = new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId('lfg_join').setLabel('Join LFG').setEmoji('🟢').setStyle(ButtonStyle.Success), new ButtonBuilder().setCustomId('lfg_close').setLabel('Close').setEmoji('🔴').setStyle(ButtonStyle.Danger)); return i.reply({ embeds: [embed('🎯 RANKED LFG', `👤 ${i.user}\n🆔 ${lfg.id}\n\n${lfg.description}`)], components: [row] }); }
      if (i.customId === 'rankup_modal') return i.reply({ embeds: [embed('🏅 Rank review submitted', 'Your proof has been sent to CPL staff for review.', colors.gold)], ephemeral: true });
      if (i.customId === 'register_modal') return i.reply({ embeds: [embed('✅ Registration submitted', 'Your tournament registration has been sent to CPL staff. Do not share private payment details publicly.', colors.green)], ephemeral: true });
      if (i.customId === 'report_modal' || i.customId === 'cheat_modal') return i.reply({ embeds: [embed('🚨 Report submitted', 'Your private report is queued for authorized staff. No automatic punishment has been applied.', colors.gold)], ephemeral: true });
      if (i.customId === 'suggest_modal') return i.reply({ embeds: [embed('💡 Suggestion submitted', 'The community can now review and vote on your suggestion.', colors.cyan)] });
    }
    if (!i.isChatInputCommand()) return;
    const n = i.commandName;
    if (n === 'ping') return i.reply({ embeds: [embed('🏓 Pong!', `API: ${client.ws.ping}ms\nBot: online`)] });
    if (n === 'about') return i.reply({ embeds: [embed('🏆 CPL — Competitive Play League', 'Competitive gaming, tournaments, 5v5s, scrims, ranked LFG, teams, coaching, and community events.', colors.gold)] });
    if (n === 'botinfo') return i.reply({ embeds: [embed('⚙️ CPL Bot 1', `Version: 0.2.0\nServers: ${client.guilds.cache.size}\nMembers: ${client.guilds.cache.reduce((sum,g) => sum + (g.memberCount ?? 0), 0)}\nUptime: ${Math.floor((client.uptime ?? 0) / 1000)}s\nStorage: ${dbPath}`)] });
    if (n === 'help') return i.reply({ embeds: [embed('CPL COMMAND CENTER', 'Use the category buttons to explore member, competition, and staff workflows.')], components: helpRows() });
    if (n === 'roles') return i.reply({ embeds: [embed('🎭 CPL ROLE CENTER', 'Choose platform, player type, LFG, and region roles below.')], components: roleRow(), ephemeral: true });
    if (n === 'rank') { const value = i.options.getString('value'); if (value) { const normalized = ranks.find(r => r.toLowerCase() === value.trim().toLowerCase()); if (!normalized) return i.reply({ content: 'Please enter a valid Rainbow Six Siege rank, such as Emerald II or Champion.', ephemeral: true }); db.ranks[i.user.id] = normalized; save(); } return i.reply({ embeds: [embed('🏅 RANK PROFILE', `Current rank: **${db.ranks[i.user.id] ?? 'Not set'}**\nUse the /rankup command to submit proof.`)], ephemeral: true }); }
    if (n === 'rankup') return i.showModal(modal('rankup_modal','Submit Rank Proof',[['rank','New rank',TextInputStyle.Short,true],['evidence','Screenshot or evidence link',TextInputStyle.Paragraph,true]]));
    if (n === 'lfg') return i.showModal(modal('lfg_modal','Create CPL LFG',[['description','Game, platform, rank, region, players needed, mic, and description',TextInputStyle.Paragraph,true]]));
    if (n === 'register') return i.showModal(modal('register_modal','Tournament Registration',[['team','Team name and captain',TextInputStyle.Short,true],['roster','Player 1, Player 2, Player 3, Player 4, Sub',TextInputStyle.Paragraph,true],['details','Platform, maps, sponsor, payment method, and payout status',TextInputStyle.Paragraph,true]]));
    if (n === 'report' || n === 'cheat-report') return i.showModal(modal(n === 'report' ? 'report_modal' : 'cheat_modal', n === 'report' ? 'Private Player Report' : 'Private Cheating Report',[['subject','Player, team, match, or tournament',TextInputStyle.Short,true],['details','Description and evidence link',TextInputStyle.Paragraph,true]]));
    if (n === 'suggest') return i.showModal(modal('suggest_modal','CPL Community Suggestion',[['suggestion','Your idea',TextInputStyle.Paragraph,true]]));
    if (n === 'team') { const sub = i.options.getSubcommand(); const existing = db.teams.find(t => t.captainId === i.user.id || t.players.includes(i.user.id) || t.subs.includes(i.user.id)); if (sub === 'create') { if (existing) return i.reply({ content: 'You are already in a team.', ephemeral: true }); const team: Team = { name: i.options.getString('name',true), captainId: i.user.id, players: [i.user.id], subs: [], platform: i.options.getString('platform',true), region: i.options.getString('region',true), createdAt: new Date().toISOString() }; db.teams.push(team); save(); return i.reply({ embeds: [embed('✅ Team created', `**${team.name}**\n👑 Captain: ${i.user}\n🎮 ${team.platform} · 🌎 ${team.region}`, colors.green)], ephemeral: true }); } if (!existing) return i.reply({ content: 'You are not linked to a CPL team.', ephemeral: true }); if (sub === 'profile') return i.reply({ embeds: [embed(`🏆 ${existing.name}`, `👑 Captain: <@${existing.captainId}>\n👤 Players: ${existing.players.map(x => `<@${x}>`).join(', ') || 'None'}\n🔄 Subs: ${existing.subs.map(x => `<@${x}>`).join(', ') || 'None'}\n🎮 ${existing.platform} · 🌎 ${existing.region}`)] }); if (sub === 'leave') { if (existing.captainId === i.user.id) return i.reply({ content: 'Captains must transfer or disband the team.', ephemeral: true }); existing.players = existing.players.filter(x => x !== i.user.id); existing.subs = existing.subs.filter(x => x !== i.user.id); save(); return i.reply({ content: 'You left the team.', ephemeral: true }); } if (existing.captainId !== i.user.id) return i.reply({ content: 'Only the captain can change the roster.', ephemeral: true }); const user = i.options.getUser('user'); if (sub === 'add' && user && !existing.players.includes(user.id)) existing.players.push(user.id); if (sub === 'remove' && user) existing.players = existing.players.filter(x => x !== user.id); if (sub === 'disband') db.teams = db.teams.filter(t => t !== existing); save(); return i.reply({ content: `✅ Team ${sub} completed.`, ephemeral: true }); }
    if (n === 'teamfinder') return i.reply({ embeds: [embed('🏆 TEAM FINDER', 'Create team recruitment posts with team, platform, region, rank, role, Apply, and Close actions. The next modal collects the post details.')], ephemeral: true });
    if (n === 'maps') return i.reply({ embeds: [embed('🗺️ CPL-APPROVED MAPS', 'Bank · Border · Clubhouse · Coastline · Consulate · Emerald Plains · Kafe Dostoyevsky · Oregon · Skyscraper · Theme Park · Villa')], ephemeral: true });
    if (n === 'stats' || n === 'teamstats' || n === 'leaderboard' || n === 'mvp') return i.reply({ embeds: [embed(`📊 ${n.toUpperCase()}`, 'Stats are updated from approved match results. Track matches, wins, losses, maps, kills, deaths, assists, K/D, MVPs, tournament wins, and prize money.')], ephemeral: n === 'stats' });
    if (n === 'tournament' || n === 'bracket' || n === 'match' || n === 'schedule') return i.reply({ embeds: [embed(`🏆 ${n.toUpperCase()}`, isStaff(i) ? 'Staff control flow ready: create, schedule, start, pause, resume, end, bracket, results, disputes, and evidence.' : 'Upcoming CPL Season 04 Playoffs · Registration open · 5v5 single elimination.')], ephemeral: true });
    if (['warn','warnings','timeout','kick','ban','clear','announce','config','dashboard'].includes(n)) { if (!staffGuard(i)) return i.reply({ content: '🔒 Staff permissions are required.', ephemeral: true }); if (n === 'warn') { const user = i.options.getUser('user',true); const reason = i.options.getString('reason',true); db.warnings[user.id] ??= []; db.warnings[user.id].push(reason); save(); } if (n === 'warnings') { const user = i.options.getUser('user',true); return i.reply({ embeds: [embed('📜 Warnings', `<@${user.id}> has ${db.warnings[user.id]?.length ?? 0} warning(s).\n${(db.warnings[user.id] ?? []).map((x,j) => `${j+1}. ${x}`).join('\n') || 'None'}`)], ephemeral: true }); } if (n === 'timeout') { const member = i.options.getMember('user') as GuildMember | null; if (member) await member.timeout(i.options.getInteger('minutes',true)*60_000); } if (n === 'kick') { const member = i.options.getMember('user') as GuildMember | null; if (member?.kickable) await member.kick('CPL staff action'); } if (n === 'ban') { const member = i.options.getMember('user') as GuildMember | null; if (member?.bannable) await member.ban({ reason: 'CPL staff action' }); } if (n === 'clear' && i.channel?.isTextBased() && 'bulkDelete' in i.channel) await (i.channel as TextChannel).bulkDelete(Math.min(i.options.getInteger('amount',true),100)); return i.reply({ embeds: [embed('✅ Staff action complete', `${n} completed and logged.`)], ephemeral: true }); }
    if (n === 'ticket') { if (!i.guild) return replyError(i,'Tickets can only be opened inside a server.'); const channel = await i.guild.channels.create({ name: `ticket-${i.user.username}`.slice(0,90), type: ChannelType.GuildText, permissionOverwrites: [{ id: i.guild.id, deny: ['ViewChannel'] }, { id: i.user.id, allow: ['ViewChannel','SendMessages','ReadMessageHistory'] }] }); const row = new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId('ticket_close').setLabel('Close Ticket').setEmoji('🔒').setStyle(ButtonStyle.Danger)); await channel.send({ content: `${i.user}`, embeds: [embed('🎫 CPL SUPPORT TICKET','Describe your issue. Authorized staff will assist you privately.')], components: [row] }); return i.reply({ content: `✅ Ticket created: ${channel}`, ephemeral: true }); }
    const simple: Record<string,string> = { coach:'🎓 Coaching Center: find coaches, apply, request coaching, VOD reviews, advice, aim, game sense, maps, communication, and team strategy.', payment:'💰 Payment status is private: Pending, Paid, Not Paid, or Review Required.', payout:'💵 Payout details are private and staff-controlled.', notifications:'🔔 Notification preferences are ready for tournaments, matches, LFG, scrims, ranks, and announcements.', news:'📰 CPL updates: tournaments, schedules, rules, community news, and new features.', clips:'📸 Recent and featured CPL clips.' }; if (simple[n]) return i.reply({ embeds: [embed(`CPL · ${n.toUpperCase()}`, simple[n])], ephemeral: true });
  } catch (error) { console.error(error); if (i.isRepliable() && !i.replied && !i.deferred) await replyError(i,'Please try again or contact CPL staff if the problem continues.'); }
});

await client.login(token);
